import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Matthew Palacio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<section className={styles.aboveTheFold}>
					<h1>Matthew Palacio</h1>
					<nav>
						<ul>
							<li>
								<Link href="#projects">
									<a>Projects</a>
								</Link>
							</li>
							<li>
								<Link href="#about">
									<a>About</a>
								</Link>
							</li>
							<li>
								<Link href="#contact">
									<a>Contact</a>
								</Link>
							</li>
						</ul>
					</nav>
				</section>

				<section>
					<h2>Projects</h2>
				</section>

				<section>
					<h2>About</h2>
				</section>

				<section>
					<h2>Contact</h2>
				</section>
			</main>

			<footer>Built with NextJS</footer>
		</div>
	);
}
